### ISSUE TITLE
IE clear input bug

### ISSUE THREAD

**Issue by jeffkevin** [twitter/typeahead.js#1052] opened 2014-11-19 02:35 UTC
It is a feature in the late IE browsers to show an 'x' or a clear button in input fields. But in conjunction with typeahead the clear button clears only the type ahead input not the real input field.

To recreate the bug, do the following (IE Browser only):
1. Type anything in the inputfield.
2. Clear the input using your mouse by clicking the x mark beside it.
3. Remove input fields focus.

**Expected result:** the input field should be empty after focusout.
**Current result:** the input returns the text that has been cleared after focusout.

**Comment by jharding** [comment] 2015-04-25 11:47
Looks like this was fixed in v0.11 (at least I'm unable to reproduce the issue).

**Closed by jharding** 2015-04-25 11:47 UTC
