### ISSUE TITLE
Results hidden for small datasets

### ISSUE THREAD

**Issue by brw2650** [twitter/typeahead.js#1481] opened 2016-02-25 13:07 UTC
I've found that some of my results are being hidden, sometimes all of them.
Changing

```
 function async(suggestions) {
                    suggestions = suggestions || [];
                    if (!canceled && rendered < that.limit) {
                        that.cancel = $.noop;
                        rendered += suggestions.length;
                        that._append(query, suggestions.slice(0, that.limit - rendered));
                        that.async && that.trigger("asyncReceived", query);
                    }
                }
```

to

```
 function async(suggestions) {
                    suggestions = suggestions || [];
                    if (!canceled && rendered < that.limit) {
                        that.cancel = $.noop;
                        that._append(query, suggestions.slice(0, that.limit - rendered));
                        rendered += suggestions.length;
                        that.async && that.trigger("asyncReceived", query);
                    }
                }
```

has fixed it for me, is this a bug?

**Comment by jk3us** [comment] 2016-03-08 17:04
More discussion at #1415

**Comment by jlbooker** [comment] 2016-11-13 00:44
Duplicate of #1232

**Closed as completed** 2022-10-25 09:14 UTC
