### ISSUE TITLE
bloodhound multiple data backspace issue

### ISSUE THREAD

**Issue by dcoder50** [twitter/typeahead.js#1024] opened 2014-10-12 10:17 UTC
I have two sets of data in json data format. When I search the city dataset I can search over and over with no issue, once I do a search within the zipcode dataset it returns the data once, after pressing the backspace key or clearing out the input the javascript gives the following error.
Uncaught TypeError: undefined is not a function typeahead.bundle.js:998

my code:

```
 var Cities = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('city'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  prefetch: 'data/city.json'
});
 
var zipCodes = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('zipcode'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  prefetch: 'data/zip.json'
});

Cities.initialize();
zipCodes.initialize();
 
$('.typeahead').typeahead({
  highlight: true
},
{
  name: 'city',
  displayKey: 'city',
  source: Cities.ttAdapter(),
  templates: {
    header: '<h3>Matching Cities</h3>'
  }
},
{
  name: 'zipcode',
  displayKey: 'zipcode',
  source: zipCodes.ttAdapter(),
  templates: {
    header: '<h3>Matching Zipcodes</h3>'
  }
});
```

**Comment by jharding** [comment] 2015-04-26 06:12
Pretty sure this is a duplicate of #1039.

**Closed by jharding** 2015-04-26 06:12 UTC
Labels: duplicate
