### ISSUE TITLE
Turning off local storage

### ISSUE THREAD

**Issue by careyestes** [twitter/typeahead.js#943] opened 2014-08-12 21:30 UTC
Is there a setting to turn off local storage? The JSON is larger than the local storage limit, so I get this error:

Uncaught QuotaExceededError:...

It still fetches properly, but I was wondering if I could turn off the attempt to store locally. I can comment this line:

// this.storage = this.cacheKey ? new PersistentStorage(this.cacheKey) : null;

which works, but I would rather leave the vendor file alone if possible.

**Comment by jharding** [comment] 2015-04-27 04:18
Closing as duplicate of #920.

**Closed by jharding** 2015-04-27 04:18 UTC
Labels: bloodhound
